# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/project/lib
  environment:
      NODE_ENV: test
  docker:
    - image: circleci/node:8

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-lib-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-lib-{{ .Branch }}-
            - v1-lib-
      - run: npm install
      - save_cache:
          key: v1-lib-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - lib

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test

  test-coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test:cov
      - run:
          name: Report coverage stats for non-PRs
          command: |
            if [[ -z $CI_PULL_REQUEST ]]; then
              cat ./coverage/lcov.info | ./node_modules/.bin/codecov
            fi

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-coverage:
          requires:
            - install
      - lint:
          requires:
            - install
